# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainguiVerticalChat.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import requests
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QImage, QPixmap
from src.classes.bag import BagObat
from src.classes.obat import Obat
from src.classes.ListObat import ListObat
from src.classes.ListOfDokter import ListOfDokter

db = ListObat(source="database/obat.csv")
cart = BagObat()
ListDr = ListOfDokter()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(717, 545)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.labelFooter = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.labelFooter.setFont(font)
        self.labelFooter.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.labelFooter.setObjectName("labelFooter")
        self.gridLayout.addWidget(self.labelFooter, 11, 0, 1, 1)
        self.btnBack = QtWidgets.QPushButton(self.centralwidget)
        self.btnBack.setObjectName("btnBack")
        self.gridLayout.addWidget(self.btnBack, 1, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageHome = QtWidgets.QWidget()
        self.pageHome.setObjectName("pageHome")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pageHome)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelHead = QtWidgets.QLabel(self.pageHome)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.labelHead.setFont(font)
        self.labelHead.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHead.setIndent(-1)
        self.labelHead.setObjectName("labelHead")
        self.verticalLayout_2.addWidget(self.labelHead)
        self.btnCariDokter = QtWidgets.QPushButton(self.pageHome)
        self.btnCariDokter.setObjectName("btnCariDokter")
        self.verticalLayout_2.addWidget(self.btnCariDokter)
        self.btnBeliObat = QtWidgets.QPushButton(self.pageHome)
        self.btnBeliObat.setObjectName("btnBeliObat")
        self.verticalLayout_2.addWidget(self.btnBeliObat)
        self.btChat = QtWidgets.QPushButton(self.pageHome)
        self.btChat.setObjectName("btChat")
        self.verticalLayout_2.addWidget(self.btChat)
        self.stackedWidget.addWidget(self.pageHome)
        self.pageObat = QtWidgets.QWidget()
        self.pageObat.setObjectName("pageObat")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.pageObat)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.obat1 = QtWidgets.QWidget(self.pageObat)
        self.obat1.setObjectName("obat1")
        self.Obat1 = QtWidgets.QVBoxLayout(self.obat1)
        self.Obat1.setObjectName("Obat1")
        self.label_3 = QtWidgets.QLabel(self.obat1)
        self.label_3.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_3.setObjectName("label_3")
        self.Obat1.addWidget(self.label_3)
        self.label = QtWidgets.QLabel(self.obat1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.Obat1.addWidget(self.label)
        self.label_7 = QtWidgets.QLabel(self.obat1)
        self.label_7.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_7.setObjectName("label_7")
        self.Obat1.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.obat1)
        self.label_8.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_8.setObjectName("label_8")
        self.Obat1.addWidget(self.label_8)
        self.pushButton_2 = QtWidgets.QPushButton(self.obat1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.Obat1.addWidget(self.pushButton_2)
        self.gridLayout_2.addWidget(self.obat1, 0, 0, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.pageObat)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_22 = QtWidgets.QLabel(self.widget_5)
        self.label_22.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_6.addWidget(self.label_22)
        self.label_30 = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_6.addWidget(self.label_30)
        self.label_32 = QtWidgets.QLabel(self.widget_5)
        self.label_32.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_6.addWidget(self.label_32)
        self.label_34 = QtWidgets.QLabel(self.widget_5)
        self.label_34.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_6.addWidget(self.label_34)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_6.addWidget(self.pushButton_7)
        self.gridLayout_2.addWidget(self.widget_5, 1, 3, 1, 1)
        self.cart = QtWidgets.QWidget(self.pageObat)
        self.cart.setObjectName("cart")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.cart)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton = QtWidgets.QPushButton(self.cart)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 3, 2, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.cart)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_4.addWidget(self.pushButton_13, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.cart)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.cart)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_4.addWidget(self.pushButton_14, 3, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.cart)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.gridLayout_4.addWidget(self.comboBox, 2, 0, 1, 2)
        self.textBrowser = QtWidgets.QTextBrowser(self.cart)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_4.addWidget(self.textBrowser, 1, 0, 1, 3)
        self.gridLayout_2.addWidget(self.cart, 8, 5, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.pageObat)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_16 = QtWidgets.QLabel(self.widget_2)
        self.label_16.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_3.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_3.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.widget_2)
        self.label_18.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_3.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.widget_2)
        self.label_19.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_3.addWidget(self.label_19)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_3.addWidget(self.pushButton_4)
        self.gridLayout_2.addWidget(self.widget_2, 0, 3, 1, 1)
        self.widget_7 = QtWidgets.QWidget(self.pageObat)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_24 = QtWidgets.QLabel(self.widget_7)
        self.label_24.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_8.addWidget(self.label_24)
        self.label_42 = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_8.addWidget(self.label_42)
        self.label_43 = QtWidgets.QLabel(self.widget_7)
        self.label_43.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_8.addWidget(self.label_43)
        self.label_38 = QtWidgets.QLabel(self.widget_7)
        self.label_38.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_8.addWidget(self.label_38)
        self.pushButton_9 = QtWidgets.QPushButton(self.widget_7)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_8.addWidget(self.pushButton_9)
        self.gridLayout_2.addWidget(self.widget_7, 8, 2, 1, 1)
        self.widget = QtWidgets.QWidget(self.pageObat)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_13 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.gridLayout_2.addWidget(self.widget, 0, 2, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.pageObat)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_20 = QtWidgets.QLabel(self.widget_3)
        self.label_20.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_4.addWidget(self.label_20)
        self.label_26 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_4.addWidget(self.label_26)
        self.label_27 = QtWidgets.QLabel(self.widget_3)
        self.label_27.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_4.addWidget(self.label_27)
        self.label_28 = QtWidgets.QLabel(self.widget_3)
        self.label_28.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_4.addWidget(self.label_28)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_4.addWidget(self.pushButton_5)
        self.gridLayout_2.addWidget(self.widget_3, 1, 0, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.pageObat)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_23 = QtWidgets.QLabel(self.widget_6)
        self.label_23.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_7.addWidget(self.label_23)
        self.label_35 = QtWidgets.QLabel(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_7.addWidget(self.label_35)
        self.label_36 = QtWidgets.QLabel(self.widget_6)
        self.label_36.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_7.addWidget(self.label_36)
        self.label_37 = QtWidgets.QLabel(self.widget_6)
        self.label_37.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_7.addWidget(self.label_37)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_7.addWidget(self.pushButton_8)
        self.gridLayout_2.addWidget(self.widget_6, 8, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.pageObat)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_21 = QtWidgets.QLabel(self.widget_4)
        self.label_21.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_5.addWidget(self.label_21)
        self.label_29 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_5.addWidget(self.label_29)
        self.label_31 = QtWidgets.QLabel(self.widget_4)
        self.label_31.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_5.addWidget(self.label_31)
        self.label_33 = QtWidgets.QLabel(self.widget_4)
        self.label_33.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_5.addWidget(self.label_33)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_5.addWidget(self.pushButton_6)
        self.gridLayout_2.addWidget(self.widget_4, 1, 2, 1, 1)
        self.widget_8 = QtWidgets.QWidget(self.pageObat)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_25 = QtWidgets.QLabel(self.widget_8)
        self.label_25.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_9.addWidget(self.label_25)
        self.label_39 = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_9.addWidget(self.label_39)
        self.label_41 = QtWidgets.QLabel(self.widget_8)
        self.label_41.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_9.addWidget(self.label_41)
        self.label_40 = QtWidgets.QLabel(self.widget_8)
        self.label_40.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_9.addWidget(self.label_40)
        self.pushButton_10 = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_9.addWidget(self.pushButton_10)
        self.gridLayout_2.addWidget(self.widget_8, 8, 3, 1, 1)
        self.util = QtWidgets.QWidget(self.pageObat)
        self.util.setObjectName("util")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.util)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_12 = QtWidgets.QPushButton(self.util)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_3.addWidget(self.pushButton_12, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.util)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 4, 0, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.util)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_3.addWidget(self.pushButton_11, 3, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.util)
        self.lineEdit_3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_3.addWidget(self.lineEdit_3, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.util)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.util)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.util)
        self.lineEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.util)
        self.lineEdit_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_3.addWidget(self.lineEdit_2, 2, 1, 1, 1)
        self.btBrowse = QtWidgets.QPushButton(self.util)
        self.btBrowse.setObjectName("btBrowse")
        self.gridLayout_3.addWidget(self.btBrowse, 5, 1, 1, 1)
        self.gridLayout_2.addWidget(self.util, 0, 5, 2, 1)
        self.stackedWidget.addWidget(self.pageObat)
        self.page_dokter = QtWidgets.QWidget()
        self.page_dokter.setObjectName("page_dokter")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.page_dokter)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.AsrayMedika = QtWidgets.QLabel(self.page_dokter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AsrayMedika.sizePolicy().hasHeightForWidth())
        self.AsrayMedika.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.AsrayMedika.setFont(font)
        self.AsrayMedika.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.AsrayMedika.setTextFormat(QtCore.Qt.PlainText)
        self.AsrayMedika.setAlignment(QtCore.Qt.AlignCenter)
        self.AsrayMedika.setObjectName("AsrayMedika")
        self.verticalLayout_12.addWidget(self.AsrayMedika)
        self.lbl_pilihDokter = QtWidgets.QLabel(self.page_dokter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_pilihDokter.sizePolicy().hasHeightForWidth())
        self.lbl_pilihDokter.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_pilihDokter.setFont(font)
        self.lbl_pilihDokter.setObjectName("lbl_pilihDokter")
        self.verticalLayout_12.addWidget(self.lbl_pilihDokter)
        self.Cbb_DOkter = QtWidgets.QComboBox(self.page_dokter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Cbb_DOkter.sizePolicy().hasHeightForWidth())
        self.Cbb_DOkter.setSizePolicy(sizePolicy)
        self.Cbb_DOkter.setEditable(False)
        self.Cbb_DOkter.setDuplicatesEnabled(False)
        self.Cbb_DOkter.setObjectName("Cbb_DOkter")
        self.verticalLayout_12.addWidget(self.Cbb_DOkter)
        self.lbl_pilihJadwal = QtWidgets.QLabel(self.page_dokter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_pilihJadwal.sizePolicy().hasHeightForWidth())
        self.lbl_pilihJadwal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_pilihJadwal.setFont(font)
        self.lbl_pilihJadwal.setObjectName("lbl_pilihJadwal")
        self.verticalLayout_12.addWidget(self.lbl_pilihJadwal)

        self.Cbb_Jadwal = QtWidgets.QComboBox(self.page_dokter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Cbb_Jadwal.sizePolicy().hasHeightForWidth())
        self.Cbb_Jadwal.setSizePolicy(sizePolicy)
        self.Cbb_Jadwal.setObjectName("Cbb_Jadwal")
        self.verticalLayout_12.addWidget(self.Cbb_Jadwal)

        self.Cbb_Jadwal.clear()

        self.Tbb_1 = QtWidgets.QTextBrowser(self.page_dokter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tbb_1.sizePolicy().hasHeightForWidth())
        self.Tbb_1.setSizePolicy(sizePolicy)
        self.Tbb_1.setObjectName("Tbb_1")
        self.verticalLayout_12.addWidget(self.Tbb_1)
        
        self.Btt_Submit = QtWidgets.QPushButton(self.page_dokter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btt_Submit.sizePolicy().hasHeightForWidth())
        self.Btt_Submit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Btt_Submit.setFont(font)
        self.Btt_Submit.setObjectName("Btt_Submit")
        self.Tbb_1.clear()

        self.verticalLayout_12.addWidget(self.Btt_Submit)
        self.stackedWidget.addWidget(self.page_dokter)
        self.page_chat = QtWidgets.QWidget()
        self.page_chat.setObjectName("page_chat")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_chat)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.page_chat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_10.addWidget(self.label_10)
        self.chatBox = QtWidgets.QTextBrowser(self.page_chat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chatBox.sizePolicy().hasHeightForWidth())
        self.chatBox.setSizePolicy(sizePolicy)
        self.chatBox.setObjectName("chatBox")
        self.verticalLayout_10.addWidget(self.chatBox)
        self.lineSendMsg = QtWidgets.QLineEdit(self.page_chat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineSendMsg.sizePolicy().hasHeightForWidth())
        self.lineSendMsg.setSizePolicy(sizePolicy)
        self.lineSendMsg.setObjectName("lineSendMsg")
        self.verticalLayout_10.addWidget(self.lineSendMsg)
        self.btSendMsg = QtWidgets.QPushButton(self.page_chat)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btSendMsg.setFont(font)
        self.btSendMsg.setObjectName("btSendMsg")
        self.verticalLayout_10.addWidget(self.btSendMsg, 0, QtCore.Qt.AlignRight)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_10.addItem(spacerItem)
        self.stackedWidget.addWidget(self.page_chat)
        self.gridLayout.addWidget(self.stackedWidget, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 717, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Asray Medika App"))
        self.labelFooter.setText(_translate("MainWindow", "Made with love by Asray Medika"))
        self.btnBack.setText(_translate("MainWindow", "Home"))
        self.labelHead.setText(_translate("MainWindow", "AsrayMedika+"))
        self.btnCariDokter.setText(_translate("MainWindow", "Cari Dokter"))
        self.btnBeliObat.setText(_translate("MainWindow", "Beli Obat"))
        self.btChat.setText(_translate("MainWindow", "Chat with Chubbot"))
        self.label_3.setText(_translate("MainWindow", "gambar 1"))
        self.label.setText(_translate("MainWindow", "nama obat 1"))
        self.label_7.setText(_translate("MainWindow", "desk 1"))
        self.label_8.setText(_translate("MainWindow", "harga 1"))
        self.pushButton_2.setText(_translate("MainWindow", "add 1"))
        self.label_22.setText(_translate("MainWindow", "gambar 5"))
        self.label_30.setText(_translate("MainWindow", "nama obat 6"))
        self.label_32.setText(_translate("MainWindow", "desk 6"))
        self.label_34.setText(_translate("MainWindow", "harga 6"))
        self.pushButton_7.setText(_translate("MainWindow", "add 6"))
        self.pushButton.setText(_translate("MainWindow", "Checkout"))
        self.pushButton_13.setText(_translate("MainWindow", "Remove"))
        self.label_4.setText(_translate("MainWindow", "Cart"))
        self.pushButton_14.setText(_translate("MainWindow", "Reset"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "gambar 3"))
        self.label_17.setText(_translate("MainWindow", "nama obat 3"))
        self.label_18.setText(_translate("MainWindow", "desk 3"))
        self.label_19.setText(_translate("MainWindow", "harga 3"))
        self.pushButton_4.setText(_translate("MainWindow", "add 3"))
        self.label_24.setText(_translate("MainWindow", "gambar 8"))
        self.label_42.setText(_translate("MainWindow", "nama obat 8"))
        self.label_43.setText(_translate("MainWindow", "desk 8"))
        self.label_38.setText(_translate("MainWindow", "harga 8"))
        self.pushButton_9.setText(_translate("MainWindow", "add 8"))
        self.label_6.setText(_translate("MainWindow", "gambar 2"))
        self.label_13.setText(_translate("MainWindow", "nama obat 2"))
        self.label_14.setText(_translate("MainWindow", "desk 2"))
        self.label_15.setText(_translate("MainWindow", "harga 2"))
        self.pushButton_3.setText(_translate("MainWindow", "add 2"))
        self.label_20.setText(_translate("MainWindow", "gambar 3"))
        self.label_26.setText(_translate("MainWindow", "nama obat 4"))
        self.label_27.setText(_translate("MainWindow", "desk 4"))
        self.label_28.setText(_translate("MainWindow", "harga 4"))
        self.pushButton_5.setText(_translate("MainWindow", "add 4"))
        self.label_23.setText(_translate("MainWindow", "gambar 7"))
        self.label_35.setText(_translate("MainWindow", "nama obat 7"))
        self.label_36.setText(_translate("MainWindow", "desk 7"))
        self.label_37.setText(_translate("MainWindow", "harga 7"))
        self.pushButton_8.setText(_translate("MainWindow", "add 7"))
        self.label_21.setText(_translate("MainWindow", "gambar 4"))
        self.label_29.setText(_translate("MainWindow", "nama obat 5"))
        self.label_31.setText(_translate("MainWindow", "desk 5"))
        self.label_33.setText(_translate("MainWindow", "harga 5"))
        self.pushButton_6.setText(_translate("MainWindow", "add 5"))
        self.label_25.setText(_translate("MainWindow", "gambar 9"))
        self.label_39.setText(_translate("MainWindow", "nama obat 9"))
        self.label_41.setText(_translate("MainWindow", "desk 9"))
        self.label_40.setText(_translate("MainWindow", "harga 9"))
        self.pushButton_10.setText(_translate("MainWindow", "add 9"))
        self.pushButton_12.setText(_translate("MainWindow", "Search"))
        self.label_9.setText(_translate("MainWindow", "Upload Receipt"))
        self.pushButton_11.setText(_translate("MainWindow", "Add to cart"))
        self.label_5.setText(_translate("MainWindow", "Result"))
        self.label_2.setText(_translate("MainWindow", "Search"))
        self.btBrowse.setText(_translate("MainWindow", "Browse"))
        self.AsrayMedika.setText(_translate("MainWindow", "AsrayMedika+"))
        self.lbl_pilihDokter.setText(_translate("MainWindow", "Pilih Dokter:"))
        self.lbl_pilihJadwal.setText(_translate("MainWindow", "Pilih Jadwal:"))
        self.Btt_Submit.setText(_translate("MainWindow", "Submit"))
        self.label_10.setText(_translate("MainWindow", "Hi! My name is Chubbot, ask me anything"))
        self.btSendMsg.setText(_translate("MainWindow", "Send"))
        self.initElement(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.chatBox.setFont(font)
        self.Tbb_1.setFont(font)
    
    def updateTextBox2(self):
        ''' New Value is the changed value of comboBox1
            Do whatever you want to do with it here
            for eg. '''
        self.Tbb_1.clear()
      
        newValue = self.Cbb_DOkter.currentText()
        valueJadwal = self.Cbb_Jadwal.currentText()
        
        ListDr = ListOfDokter()
        for i in range(len(ListDr.listDokter)):
            if (str(newValue)==str(ListDr.listDokter[i].getNamaDokter())):
                #for j in range(len(ListDr.listDokter[i].listJadwal)):
                   #self.Cbb_Jadwal.addItem(ListDr.listDokter[i].listJadwal[j].getJadwalAsDate())
                self.Tbb_1.insertPlainText("Terimakasih telah membuat janji konsultasi, berikut adalah Detail dokter dan jadwal konsultasi anda: \n" ) 
                self.Tbb_1.insertPlainText("ID Dokter: " + str(ListDr.listDokter[i]._id)+"\n")
                self.Tbb_1.insertPlainText("Nama: " + str(ListDr.listDokter[i]._name)+"\n")
                self.Tbb_1.insertPlainText("Pendidikan: "+str(ListDr.listDokter[i]._gelar)+"\n")
                self.Tbb_1.insertPlainText("Jadwal yang anda pilih : "+valueJadwal)
                for j in range (len(ListDr.listDokter[i].listJadwal)):
                    if (str(ListDr.listDokter[i].listJadwal[j].getJadwalAsDate())==valueJadwal):
                        ListDr.listDokter[i].listJadwal[j]._indikatorBooked = str(0)
                        ListDr.Checkout(int(ListDr.listDokter[i].getIdDokter()),int(ListDr.listDokter[i].listJadwal[j].getIdJadwal())-1)
                        ListDr = ListOfDokter()
                break
    def updateTextBox1(self):
        ''' New Value is the changed value of comboBox1
            Do whatever you want to do with it here
            for eg. '''
        self.Tbb_1.clear()
        newValue = self.Cbb_DOkter.currentText()
        
        ListDr = ListOfDokter()
        for i in range(len(ListDr.listDokter)):
            if (str(newValue)==str(ListDr.listDokter[i].getNamaDokter())):
                #for j in range(len(ListDr.listDokter[i].listJadwal)):
                   #self.Cbb_Jadwal.addItem(ListDr.listDokter[i].listJadwal[j].getJadwalAsDate())
                self.Tbb_1.insertPlainText("Berikut adalah detail dokter yang anda pilih: \n" )
                self.Tbb_1.insertPlainText("ID Dokter: " + str(ListDr.listDokter[i]._id)+"\n")
                self.Tbb_1.insertPlainText("Nama: " + str(ListDr.listDokter[i]._name)+"\n")
                self.Tbb_1.insertPlainText("Pendidikan: "+str(ListDr.listDokter[i]._gelar)+"\n")
                
                break
    def updateComboBox2(self):
        ''' New Value is the changed value of comboBox1
            Do whatever you want to do with it here
            for eg. '''
        self.Cbb_Jadwal.clear()
        newValue = self.Cbb_DOkter.currentText()
        ListDr = ListOfDokter()
        for i in range(len(ListDr.listDokter)):
            if (str(newValue)==str(ListDr.listDokter[i].getNamaDokter())):
                for j in range(len(ListDr.listDokter[i].listJadwal)):
                    if (str(ListDr.listDokter[i].listJadwal[j].getIndikatorBooked())=="1"):
                        self.Cbb_Jadwal.addItem(ListDr.listDokter[i].listJadwal[j].getJadwalAsDate())
                break

    def initElement(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate

        # binding
        self.pushButton_12.clicked.connect(lambda: self.search(self.lineEdit.text()))
        self.pushButton_11.clicked.connect(lambda: self.addtocart(self.parsesearch(self.lineEdit_2.text())))
        self.pushButton_13.clicked.connect(lambda: self.removeobat(self.comboBox.currentText()))
        self.pushButton_14.clicked.connect(lambda: self.removecart())
        self.btBrowse.clicked.connect(lambda: self.browseFile())
        self.pushButton.clicked.connect(lambda: self.checkoutcart())
        self.btnBack.clicked.connect(lambda: self.backtomainmenu())
        self.btnCariDokter.clicked.connect(lambda: self.gotocaridokter())
        self.btnBeliObat.clicked.connect(lambda: self.gotobeliobat())

        for i in range(len(ListDr.listDokter)):
            self.Cbb_DOkter.addItem(ListDr.listDokter[i].getNamaDokter())
        self.Cbb_DOkter.activated.connect(lambda: self.updateTextBox1())
        self.Cbb_DOkter.activated.connect(lambda: self.updateComboBox2())
        self.Btt_Submit.clicked.connect(lambda: self.updateTextBox2())

        self.btSendMsg.clicked.connect(lambda: self.kirim(self.lineSendMsg.text()))
        self.lineSendMsg.returnPressed.connect(lambda: self.kirim(self.lineSendMsg.text()))

        self.btChat.clicked.connect(lambda: self.gotochat())

        self.loadObat()
    
    def parsesearch(self, query):
        query = query.split(" - ")

        if len(query) > 1:
            return query[0]
        else:
            return None

    def addtocart(self, id):
        if id is not None and cart.totalObat(id) < int(db.findObat(id).getStok()):
            cart.add(id)
        
        self.handlecart()
    
    def removeobat(self, id):
        if id:
            cart.remove(id)
        self.handlecart()
    
    def removecart(self):
        id = []
        for idobat, qty in cart:
            id.append(idobat)
        
        for i in id:
            cart.remove(i)
        
        self.handlecart()
    
    def handlecart(self):
        _translate = QtCore.QCoreApplication.translate
        text = ""
        self.comboBox.clear()

        q = []
        i = []
        h = []

        for idobat, qty in cart:
            harga = int(db.findObat(idobat).getHargaObat())
            self.comboBox.addItem(idobat)

            if len(text) > 0:
                text += "\n"
            
            text += str(qty)+"x"+"   "+str(idobat)+"   Rp"+str(harga*qty)

            q.append(str(qty))
            i.append(idobat)
            h.append(harga*qty)
        
        fmt = '{:<8}{:<20}{}'
        text = fmt.format('Qty', 'ID', 'Harga')
        for i, (qty, id, harga) in enumerate(zip(q,i,h)):
            text += "\n" + fmt.format(qty, id, harga)

        
        self.textBrowser.setText(_translate("MainWindow", text))

    def search(self, query):
        _translate = QtCore.QCoreApplication.translate
        search = db.searchObat(query)
        if len(search) > 0:
            self.lineEdit_2.setText(_translate("MainWindow", search[0].getIdObat()+" - "+search[0].getNamaObat()))
        else:
            self.lineEdit_2.setText(_translate("MainWindow", "Not found"))

    def loadObat(self):
        _translate = QtCore.QCoreApplication.translate
        gambar = [self.label_3, self.label_6, self.label_16, self.label_20, self.label_21, self.label_22, self.label_23, self.label_24, self.label_25]
        nama = [self.label, self.label_13, self.label_17, self.label_26, self.label_29, self.label_30, self.label_35, self.label_42, self.label_39]
        deskripsi = [self.label_7, self.label_14, self.label_18, self.label_27, self.label_31, self.label_32, self.label_36, self.label_43, self.label_41]
        harga = [self.label_8, self.label_15, self.label_19, self.label_28, self.label_33, self.label_34, self.label_37, self.label_38, self.label_40]
        btn = [self.pushButton_2, self.pushButton_3, self.pushButton_4, self.pushButton_5, self.pushButton_6, self.pushButton_7, self.pushButton_8, self.pushButton_9, self.pushButton_10]

        for i, obat in enumerate(db):
            if i >= 9: break

            image = QImage()
            image.loadFromData(requests.get(obat.getImgObat()).content)
            pixmap = QPixmap(image)
            pixmap = pixmap.scaled(86, 86, QtCore.Qt.KeepAspectRatio)
            gambar[i].setPixmap(pixmap)

            nama[i].setText(_translate("MainWindow", obat.getIdObat()+" "+obat.getNamaObat()))

            font = QtGui.QFont()
            font.setPointSize(10)
            deskripsi[i].setFont(font)
            font.setPointSize(12)
            harga[i].setFont(font)

            desc = obat.getDescObat()+"\nStok: "+ str(obat.getStok())
            deskripsi[i].setText(_translate("MainWindow", desc))

            harga[i].setText(_translate("MainWindow", "Rp"+str(obat.getHargaObat())))

            btn[i].setText(_translate("MainWindow", "Add to cart"))
            btn[i].clicked.connect(lambda checked, a=obat.getIdObat(): self.addtocart(a))
    
    def browseFile(self):
        filename = QtWidgets.QFileDialog.getOpenFileName()
        self.lineEdit_3.setText(filename[0].split("/")[-1])
        self.addFromReceipt(cart, db, source=filename[0])

    def checkoutcart(self):
        _translate = QtCore.QCoreApplication.translate
        cart.sortById()
        deskripsi = [self.label_7, self.label_14, self.label_18, self.label_27, self.label_31, self.label_32, self.label_36, self.label_43, self.label_41]
        for idobat, qty in cart:
            obat = db.findObat(idobat)
            i = db.findIdxObat(idobat)
            desc = obat.getDescObat()+"\nStok: "+ str(obat.getStok()-qty)
            deskripsi[i].setText(_translate("MainWindow", desc))
        cart.checkout(db)
        self.removecart()

    def addFromReceipt(self, cart, db, source):
        with open(source, "r") as file:
            lines = file.readlines()
            for line in lines:
                args = line.strip().split(" : ")
                namaobat = args[0]
                qty = int(args[1])
                
                search_res = db.searchObat(namaobat)
                if not search_res:
                    print(str(namaobat)+" tidak ditemukan.")
                    continue
                else:
                    obj_obat = search_res[0]
                    self.addtocart(obj_obat.getIdObat())
                    if qty > 1:
                        cart.increase(obj_obat.getIdObat(),qty-1)
                        for i in range (qty-1):
                            self.addtocart(obj_obat.gsetIdObat())
    
    def backtomainmenu(self):
        self.stackedWidget.setCurrentIndex(0)
        self.chatBox.clear()
        self.Tbb_1.clear()
    
    def gotobeliobat(self):
        self.stackedWidget.setCurrentIndex(1)
    
    def gotocaridokter(self):
        self.stackedWidget.setCurrentIndex(2)
    
    def gotochat(self):
        self.stackedWidget.setCurrentIndex(3)
        str_opening =""
        str_opening += "Selamat datang di layanan chatbot AsrayMedika+\n"
        str_opening += "Kami siap melayani berbagai keperluan anda. Masukkan command 'bantuan' untuk melihat list command yang dapat digunakan\n"
        self.chatBox.insertPlainText(str_opening+"\n")
    
    def kirim(self, query) :
        _translate = QtCore.QCoreApplication.translate
        pesanPasien = query
        pesanPasienLC =""
        pesanPasienLC = pesanPasien.lower()
        sendmsg = "Anda :\n" + pesanPasienLC
        self.chatBox.insertPlainText(_translate("MainWindow","\n"+sendmsg+"\n"))
        self.chatBox.moveCursor(QtGui.QTextCursor.End)
        pesanBot =""
        
        pesanBot = self.respon(pesanPasienLC)
        receivemsg = "Chubbot :\n" + pesanBot
        self.chatBox.insertPlainText(_translate("MainWindow","\n"+receivemsg))
        self.chatBox.moveCursor(QtGui.QTextCursor.End)
        self.lineSendMsg.clear()

    def respon(self, pesan) :
        str_pesan = ""
        if (pesan == "halo") :
            str_pesan += "Halo, ada yang bisa kami bantu?\n"
        elif (pesan == "bantuan") :
            str_pesan += "Command yang dapat diberikan\n"
            str_pesan += "0. Selesai                    \t\t: untuk menyelesaikan percakapan\n"
            str_pesan += "1. Cara konsultasi            \t: untuk melihat cara membuat janji konsultasi\n"
            str_pesan += "2. Lihat dokter               \t: untuk melihat dokter yang tersedia\n"
            str_pesan += "3. Lihat jadwal <ID Dokter>   \t: untuk melihat jadwal dokter\n"
            str_pesan += "4. Cara beli obat             \t: untuk melihat cara membeli obat\n"
            str_pesan += "5. Pengiriman obat            \t: untuk melihat metode pengiriman obat\n"
        elif (pesan == "cara konsultasi") :
            str_pesan += "Untuk membuat jadwal konsultasi\n"
            str_pesan += "1. Pilih fitur 'Dokter'\n"
            str_pesan += "2. Pilih dokter\n"
            str_pesan += "3. Pilih jadwal yang diinginkan sesuai jadwal yang tersedia setiap dokternya\n"
            str_pesan += "4. Pada laman konfirmasi, masukkan data diri anda\n"
            str_pesan += "5. Klik tombol submit\n"
            str_pesan += "6. Jadwal konsultasi anda sudah dibuat\n"
        elif (pesan == "cara beli obat") :
            str_pesan += "Untuk membeli obat\n"
            str_pesan += "1. Pilih fitur 'Apotek'\n"
            str_pesan += "2. Pilih obat yang ingin dibeli atau masukkan resep dari dokter\n"
            str_pesan += "3. Masukkan jumlah obat yang ingin dibeli\n"
            str_pesan += "4. Pada laman konfirmasi, masukkan data diri anda dan detil terkait pengiriman\n"
            str_pesan += "5. Klik tombol order\n"
            str_pesan += "6. Transaksi sudah dibuat\n"
        elif (pesan == "lihat dokter") :
            str_pesan += "Dokter yang tersedia\n\n"
            for i in range(len(ListDr.listDokter)):
                str_pesan += "ID Dokter: " + str(ListDr.listDokter[i]._id)+"\n"
                str_pesan += "Nama: " + str(ListDr.listDokter[i]._name)+"\n"
                str_pesan += "Pendidikan: "+str(ListDr.listDokter[i]._gelar)+"\n\n"
                
        elif (pesan == "lihat jadwal") :
            str_pesan += "Pilih dokter terlebih dahulu untuk melihat jadwal\n"
        elif (pesan == "lihat jadwal 1") :
            str_pesan += "Jadwal yang tersedia\n"
    
            for j in range(len(ListDr.listDokter[0].listJadwal)):
                if (str(ListDr.listDokter[0].listJadwal[j].getIndikatorBooked())=="1"):
                    str_pesan += ListDr.listDokter[0].listJadwal[j].getJadwalAsDate()+"\n"
        elif (pesan == "lihat jadwal 2") :
            str_pesan += "Jadwal yang tersedia\n"
            for j in range(len(ListDr.listDokter[1].listJadwal)):
                if (str(ListDr.listDokter[1].listJadwal[j].getIndikatorBooked())=="1"):
                        str_pesan += ListDr.listDokter[1].listJadwal[j].getJadwalAsDate()+"\n"
        elif (pesan == "lihat jadwal 3") :
            str_pesan += "Jadwal yang tersedia\n"
            for j in range(len(ListDr.listDokter[2].listJadwal)):
                if (str(ListDr.listDokter[2].listJadwal[j].getIndikatorBooked())=="1"):
                        str_pesan += ListDr.listDokter[2].listJadwal[j].getJadwalAsDate()+"\n"
        elif (pesan == "pengiriman obat") :
            str_pesan += "Untuk pengiriman obat terdapat dua metode =\n"
            str_pesan += "1. Pick-up manual, pasien datang ke apotek untuk mengambil obat\n"
            str_pesan += "2. Jasa kurir, pesanan akan dikirimkan ke lokasi pasien menggunakan jasa pengiriman dari pihak ketiga\n"
        elif (pesan == "selesai"):
            str_pesan += "Terima kasih atas kepercayaan anda dalam menggunakan AsrayMedika+\n"
            str_pesan += "Sampai jumpa di lain waktu\n"
        else :
            str_pesan += "Kamu sepertinya kebingungan dengan perintah yang bisa dikirimkan.\nKetik 'bantuan' untuk melihat command yang dapat dilakukan\n"
        return str_pesan


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
